; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=m68k-pc-linux -verify-machineinstrs | FileCheck %s

define i8 @palm_i8_i8(i8 %a, i8 %b) m68k_palmcc {
; CHECK-LABEL: palm_i8_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    move.b (5,%sp), %d0
; CHECK-NEXT:    add.b (7,%sp), %d0
; CHECK-NEXT:    rts
entry:
  %add = add i8 %a, %b
  ret i8 %add
}

define void @palm_ptr_i16(ptr nocapture %out, i16 %in) m68k_palmcc {
; CHECK-LABEL: palm_ptr_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    move.l (4,%sp), %a0
; CHECK-NEXT:    move.w (8,%sp), (%a0)
; CHECK-NEXT:    rts
entry:
  store i16 %in, ptr %out, align 2
  ret void
}
