; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=m68k-linux  -mcpu=M68020 -verify-machine-instr | FileCheck %s

define internal void @test_func(i32 %self, ptr nonnull %value) {
start:
  %2 = icmp eq i32 %self, 0
  %3 = select i1 %2, i32 0, i32 1
  switch i32 %3, label %exit [
    i32 0, label %nonnull
    i32 1, label %null
  ]

nonnull:                                              ; preds = %start
  store ptr %value, ptr null, align 2
  br label %exit

null:                                              ; preds = %start
  store ptr %value, ptr null, align 2
  br label %exit

exit:                                              ; preds = %nonnull, %null
  ret void
}